[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
color_voter_backend = "xT1sp4mfJ4rNGjwbrCNNMgFPXmUgUerAYCsoEGNKd4U"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "http://127.0.0.1:8898"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
